### ISSUE TITLE
Plug the project into Jenkins CI server.

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/AmI2C#2]
We already have Jenkins running for the purpose of SonnetAmiga project. I'll plug this project into Jenkins too. This depends on completing issue #1 first.

**Comment by rkujawa** [comment]
The Jenkins integration is up and running. Any CVS commit will automatically trigger project build in Jenkins. In case some breaks the build, he will get an email explaining what happened. 

In case you ever need to play with Jenkins interface directly (for example to start manual build or mess with project settings), you can log in via following URL: https://sonnet.uguu.waw.pl/jenkins/

Login and password same as for CVS. Please confirm that you can log in @bubbob42 @scratje .

**Comment by bubbob42** [comment]
@rkujawa: works great!

**Comment by scratje** [comment]
Seems to work for me too
