### ISSUE TITLE
Paths hardcoded in SAS/C smakefile and scoptions

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/AmI2C#3]
@bubbob42 SAS/C-specific files contain hardcoded paths to certain locations on your filesystem.

As @scratje suggested in private mail, it would be best if everyone added an assign to NDK directory and used this in smakefile/scoptions where needed. For example `NDK_3.9:include/include_h`.

**Comment by bubbob42** [comment]
> Am 24.01.2016 um 01:13 schrieb Radosław Kujawa <notifications@github.com>:
> As @scratje suggested in private mail, it would be best if everyone added an assign to NDK directory and used this in smakefile/scoptions where needed For example NDK_39:include/include_h

Absolutely - I should have changed this a long time ago anyway. :D

Will also look into the build process.

**Comment by bubbob42** [comment]
Changed smakefile's "IDIR" to "NDK_39:include/include_h/" as suggested. "DDIR" is now the current directory.

**Comment by rkujawa** [comment]
On a side note, I set `DDIR` to `../../bin` in Makefile for vbcc. At some point we'll end up with more than one class and it would probably be good to dump them into common output directory.
